-- fonts
surface.CreateFont( "font_base", {font = "Play Bold",size = 31,weight = 0,underline = false,extended = true,})
surface.CreateFont( "font_base_big", {font = "Play Bold",size = 81,weight = 500,extended = true,})
surface.CreateFont( "font_base_rotate", {font = "Play Bold",size = 38,weight = 0,extended = true,})
surface.CreateFont( "font_base_normal", {font = "Play Bold",size = 56,weight = 0,underline = false,extended = true})
surface.CreateFont( "font_base_24", {font = "Play Bold",size = 23,weight = 500,extended = true,})
surface.CreateFont( "font_base_22", {font = "Play Bold",size = 21,weight = 500,extended = true,})
surface.CreateFont( "font_base_title", {font = "Play Bold",size = 38,weight = 0,extended = true,})
surface.CreateFont( "font_base_18", {font = "Play Bold",size = 17,weight = 500,extended = true,})
surface.CreateFont( "font_base_small", {font = "Default",size = 14,weight = 300,underline = false,extended = true,})
surface.CreateFont( "font_base_12", {font = "Default",size = 11,weight = 0,underline = false,extended = true})
surface.CreateFont( "font_base_hud", {font = "Play Bold",size = 26,weight = 0,underline = false,extended = true})
surface.CreateFont( "font_base_84_normal", {font = "Play Bold",size = 84,weight = 0,underline = false,extended = true})
surface.CreateFont( "font_base_84", {font = "Play Bold",size = 84,weight = 0,underline = false,extended = true})
surface.CreateFont( "font_base_54", {font = "Play Bold",size = 53,weight = 0,underline = false,extended = true})
surface.CreateFont( "font_base_543", {font = "Play Bold",size = 30,weight = 0,underline = false,extended = true})
surface.CreateFont( "font_base_544", {font = "Play Bold",size = 50,weight = 0,underline = false,extended = true})
surface.CreateFont( "font_base_warning", {font = "Play Bold",size = 20,weight = 0,underline = false,extended = true})
surface.CreateFont( "font_notify", {font = "Play Bold",size = 18,weight = 500,extended = true})
surface.CreateFont( "font_base_45", {font = "Play Bold",size = 45,weight = 100, extended = true,})
surface.CreateFont( "font_roboto_24", { font = "Roboto", size = 24, weight = 100, extended = true })
surface.CreateFont( "font_roboto_21", { font = "Roboto", size = 21, weight = 100, extended = true })

surface.CreateFont( "font_base_big_s", {font = "Play Bold", blursize = 5, size = 81, weight = 500, extended = true})

surface.CreateFont( "font_base_large", {font = "Play Bold",extended = true,size = 100,weight = 500})
