local function AddPlayerModel( name, model )

	list.Set( "PlayerOptionsModel", name, model )
	player_manager.AddValidModel( name, model )
	
end
--кастом
AddPlayerModel( "8", "models/galactic/clones/spookyclone.mdl" )
AddPlayerModel( "9", "models/galactic/clones/104/boost.mdl" )
AddPlayerModel( "10", "models/galactic/clones/104/cdr.mdl" )
AddPlayerModel( "11", "models/galactic/clones/104/comet.mdl" )
AddPlayerModel( "12", "models/galactic/clones/104/dash.mdl" )
AddPlayerModel( "13", "models/galactic/clones/104/highofc.mdl" )
AddPlayerModel( "14", "models/galactic/clones/104/lowofc.mdl" )
AddPlayerModel( "15", "models/galactic/clones/104/nco.mdl" )
AddPlayerModel( "16", "models/galactic/clones/104/sinker.mdl" )
AddPlayerModel( "17", "models/galactic/clones/104/spittermortar.mdl" )
AddPlayerModel( "18", "models/galactic/clones/104/trooper.mdl" )
AddPlayerModel( "19", "models/galactic/clones/104/warthog.mdl" )
AddPlayerModel( "20", "models/galactic/clones/104/wildfire.mdl" )
AddPlayerModel( "21", "models/galactic/clones/104/wolfpack.mdl" )
AddPlayerModel( "22", "models/galactic/clones/501/boomer.mdl" )
AddPlayerModel( "23", "models/galactic/clones/501/cdr.mdl" )
AddPlayerModel( "24", "models/galactic/clones/501/dogma.mdl" )
AddPlayerModel( "25", "models/galactic/clones/501/echo.mdl" )
AddPlayerModel( "26", "models/galactic/clones/501/fives.mdl" )
AddPlayerModel( "27", "models/galactic/clones/501/hardcase.mdl" )
AddPlayerModel( "28", "models/galactic/clones/501/highofc.mdl" )
AddPlayerModel( "29", "models/galactic/clones/501/jesse.mdl" )
AddPlayerModel( "30", "models/galactic/clones/501/kix.mdl" )
AddPlayerModel( "31", "models/galactic/clones/501/lowofc.mdl" )
AddPlayerModel( "32", "models/galactic/clones/501/nco.mdl" )
AddPlayerModel( "33", "models/galactic/clones/501/tc.mdl" )
AddPlayerModel( "34", "models/galactic/clones/501/trooper.mdl" )
AddPlayerModel( "35", "models/galactic/clones/501tc/highofc.mdl" )
AddPlayerModel( "36", "models/galactic/clones/501tc/lowofc.mdl" )
AddPlayerModel( "37", "models/galactic/clones/501tc/nco.mdl" )
AddPlayerModel( "38", "models/galactic/clones/501tc/trooper.mdl" )
AddPlayerModel( "39", "models/galactic/clones/arc/arf.mdl" )
AddPlayerModel( "40", "models/galactic/clones/arc/cdr.mdl" )
AddPlayerModel( "41", "models/galactic/clones/arc/highofc.mdl" )
AddPlayerModel( "42", "models/galactic/clones/arc/lowofc.mdl" )
AddPlayerModel( "43", "models/galactic/clones/arc/nco.mdl" )
AddPlayerModel( "44", "models/galactic/clones/arc/null.mdl" )
AddPlayerModel( "45", "models/galactic/clones/arc/trooper.mdl" )
AddPlayerModel( "46", "models/galactic/clones/arf/cdr.mdl" )
AddPlayerModel( "47", "models/galactic/clones/arf/highofc.mdl" )
AddPlayerModel( "48", "models/galactic/clones/arf/highofc2.mdl" )
AddPlayerModel( "49", "models/galactic/clones/arf/lowofc.mdl" )
AddPlayerModel( "50", "models/galactic/clones/arf/nco.mdl" )
AddPlayerModel( "51", "models/galactic/clones/arf/trooper2.mdl" )
AddPlayerModel( "52", "models/galactic/clones/arf/trooper.mdl" )
AddPlayerModel( "53", "models/galactic/clones/cg/cdr.mdl" )
AddPlayerModel( "54", "models/galactic/clones/cg/highofc.mdl" )
AddPlayerModel( "55", "models/galactic/clones/cg/hound.mdl" )
AddPlayerModel( "56", "models/galactic/clones/cg/jek.mdl" )
AddPlayerModel( "57", "models/galactic/clones/cg/lowofc.mdl" )
AddPlayerModel( "58", "models/galactic/clones/cg/nco.mdl" )
AddPlayerModel( "59", "models/galactic/clones/cg/rys.mdl" )
AddPlayerModel( "60", "models/galactic/clones/cg/stone.mdl" )
AddPlayerModel( "61", "models/galactic/clones/cg/thire.mdl" )
AddPlayerModel( "62", "models/galactic/clones/cg/trooper.mdl" )
AddPlayerModel( "63", "models/galactic/clones/rm/cdr.mdl" )
AddPlayerModel( "64", "models/galactic/clones/rm/highofc.mdl" )
AddPlayerModel( "65", "models/galactic/clones/rm/lowofc.mdl" )
AddPlayerModel( "66", "models/galactic/clones/rm/nco.mdl" )
AddPlayerModel( "67", "models/galactic/clones/rm/trooper.mdl" )
AddPlayerModel( "68", "models/galactic/clones/rp/blueofc.mdl" )
AddPlayerModel( "69", "models/galactic/clones/rp/bluetrooper.mdl" )
AddPlayerModel( "70", "models/galactic/clones/rp/cdr.mdl" )
AddPlayerModel( "71", "models/galactic/clones/rp/highofc.mdl" )
AddPlayerModel( "72", "models/galactic/clones/rp/lowofc.mdl" )
AddPlayerModel( "73", "models/galactic/clones/rp/nco.mdl" )
AddPlayerModel( "74", "models/galactic/clones/rp/redofc.mdl" )
AddPlayerModel( "75", "models/galactic/clones/rp/redtrooper.mdl" )
AddPlayerModel( "76", "models/galactic/clones/rp/shadowofc.mdl" )
AddPlayerModel( "77", "models/galactic/clones/rp/shadowtrooper.mdl" )
AddPlayerModel( "78", "models/galactic/clones/rp/trooper.mdl" )
AddPlayerModel( "79", "models/player/trooper/cctrooper.mdl" )







--кастом
player_manager.AddValidHands( "8", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "9", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "10", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "11", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "12", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "13", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "14", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "15", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "16", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "17", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "18", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "19", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "20", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "21", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "22", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "23", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "24", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "25", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "26", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "27", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "28", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "29", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "30", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "31", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "32", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "33", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "34", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "35", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "36", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "37", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "38", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "39", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "40", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "41", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "42", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "43", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "44", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "45", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "46", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "47", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "48", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "49", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "50", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "51", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "52", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "53", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "54", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "55", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "56", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "57", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "58", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "59", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "60", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "61", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "62", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "63", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "64", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "65", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "66", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "67", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "68", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "69", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "70", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "71", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "72", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "73", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "74", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "75", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "76", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "77", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "78", "models/galactic/clones/clonearms.mdl", 0, "10000000" )
player_manager.AddValidHands( "79", "models/galactic/clones/clonearms.mdl", 0, "10000000" )

--other
-- player_manager.AddValidHands( "st MetaHub", "models/weapons/hands/hands.mdl", 0, "10000000" )
-- player_manager.AddValidHands( "off MetaHub", "models/weapons/hands/hands.mdl", 0, "10000000" )
-- player_manager.AddValidHands( "spec MetaHub", "models/weapons/hands/hands.mdl", 0, "10000000" )
-- player_manager.AddValidHands( "heavy MetaHub", "models/weapons/hands/hands.mdl", 0, "10000000" )
-- player_manager.AddValidHands( "cmd MetaHub", "models/weapons/hands/hands.mdl", 0, "10000000" )